# Generated by Django 5.1.6 on 2025-02-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='large_language_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('opensource', models.BooleanField(null=True)),
                ('reasoning', models.BooleanField(null=True)),
                ('param_number_billions', models.IntegerField(null=True)),
                ('context_window', models.IntegerField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('MMLU', models.IntegerField(null=True)),
                ('TruthfulQA', models.IntegerField(null=True)),
                ('Perplexity', models.IntegerField(null=True)),
            ],
        ),
    ]
