# Generated by Django 5.1.6 on 2025-02-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='large_language_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, null=True)),
                ('opensource', models.BooleanField(null=True)),
                ('reasoning', models.BooleanField(null=True)),
                ('param_number_billions', models.FloatField(null=True)),
                ('context_window', models.IntegerField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('MMLU', models.FloatField(null=True)),
                ('TruthfulQA', models.FloatField(null=True)),
                ('Perplexity', models.FloatField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='large_language_models',
        ),
    ]
