# Generated by Django 5.1.6 on 2025-02-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_large_language_model_delete_large_language_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='large_language_model',
            name='ndow',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='large_language_model',
            name='context_window',
            field=models.FloatField(null=True),
        ),
    ]
