# Generated by Django 5.1.6 on 2025-02-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_large_language_model_ndow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='large_language_model',
            name='context_window',
            field=models.IntegerField(null=True),
        ),
    ]
